version: '3.8'
services:
    # Spring Boot Demo API
  spring-boot-demo:
    container_name: spring-boot-demo
    build: 
      context: .
      dockerfile: Dockerfile
    image: spring-boot-demo:latest
    networks:
      - demo-net
    ports:
      - '8090:8090'
    environment:
      - spring.profiles.active=local
      - spring.config.name=spring-boot-demo

networks:
  demo-net:
    driver: bridge