version: '3.8'

services:
    
  # Keycloak
  keycloak:
    container_name: keycloak
    build: "./keycloak/"
    networks:
      - demo-net
    ports:
      - '8080:8080'
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
        interval: 5s
        timeout: 2s
        retries: 15

    # Spring Boot Demo API
  spring-boot-demo:
    container_name: spring-boot-demo
    build: 
      context: .
      dockerfile: Dockerfile
    image: spring-boot-demo:latest
    networks:
      - demo-net
    ports:
      - '8090:8090'
    environment:
      - spring.profiles.active=dev
      - spring.config.name=spring-boot-demo
      - keycloak.auth-server-url=http://keycloak:8080/auth     
    depends_on:
      keycloak:
        condition: service_healthy

networks:
  demo-net:
    driver: bridge
