version: '3.8'

services:

  # Keycloak
  keycloak:
    container_name: keycloak
    build: "./keycloak/"
    networks:
      - demonet
    ports:
      - '8080:8080'
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/auth/"]
        interval: 5s
        timeout: 2s
        retries: 15

  # Spring Boot Demo API
  spring-boot-demo:
    image: docker-public.kube.cloudapps.ms3-inc.com/spring-boot-demo:latest
    networks:
      - demonet
    ports:
      - '8090:8090'
    environment:
      - spring.profiles.active=dev
      - spring.config.name=spring-boot-demo
      - keycloak.auth-server-url=http://keycloak:8080/auth   
    depends_on:
      keycloak:
        condition: service_healthy
    
networks:
  demonet:
    driver: bridge
