#! /usr/bin/bash
sudo wget https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm 
sudo dnf install mysql80-community-release-el9-1.noarch.rpm -y 
sudo dnf install -y mysql-community-server
sudo systemctl start mysqld
sudo systemctl status mysqld
