apiVersion: v1
kind: Namespace
metadata:
  name: training
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sb-demo-api
  namespace: training
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sb-demo-api
            port: 
              number: 8090
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sb-demo-api
  name: sb-demo-api
  namespace: training
spec:
  ports:
  - port: 8090
    name: high
    protocol: TCP
    targetPort: 8090
  selector:
    app: sb-demo-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sb-demo-api
  name: sb-demo-api
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-demo-api
  strategy: {}
  template:
    metadata:
      labels:
        app: sb-demo-api
    spec:
      containers:
      - image: docker-public.kube.cloudapps.ms3-inc.com/spring-boot-demo:latest
        name: sb-demo-api
        ports:
        - containerPort: 8090
        env:
          - name: spring.config.name
            value: spring-boot-demo
          - name: spring.profiles.active
            value: local
        resources: {}