apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: dind
spec: 
  containers:
  - name: docker
    image: docker:19.03-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  - name: maven
    image: maven:3.6.3-openjdk-11
    tty: true 
    command: ['cat']
  - name: postman
    image: postman/newman
    tty: true 
    command: ['cat']
  - name: jmeter
    image: justb4/jmeter
    tty: true 
    command: ['cat']
#  - name: keycloak
#    image: jboss/keycloak
#    env: 
#      - name: KEYCLOAK_USER
#        value: admin
#      - name: KEYCLOAK_PASSWORD
#        value: admin
#      - name: KEYCLOAK_IMPORT
#        value: /home/jenkins/agent/workspace/andie-keycloak-pipeline/demo.json
  volumes:
    - name: dind-storage
      emptyDir: {}
  imagePullSecrets:
    - name: nexus